name: Test
on:
  push:
    branches:
      - master
    paths:
      - '**.yml'
      - '__tests__/**'
jobs:
  simple-upload:
    runs-on: ubuntu-latest
    continue-on-error: true
    name: Simple Test
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        out-name: Rinze1
        sql-file: __tests__/${{ github.job }}/shiny-small.sql
