name: Test
on:
  push:
    branches:
      - master
    paths:
      - '**.yml'
      - '__tests__/**'
      - 'convert'
  workflow_dispatch:
jobs:
  simple-upload:
    runs-on: ubuntu-latest
    name: Simple Test
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        name: Rinze1 (Standard)
        file: __tests__/${{ github.job }}/shiny-small
        extension: mdb
  spaced-upload:
    runs-on: ubuntu-latest
    name: Spaced Test
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        name: Rinze1 (Spaced File Name)
        file: __tests__/${{ github.job }}/shiny small
        extension: mdb
