name: Test
on:
  push:
    branches:
      - master
    paths:
      - '**.yml'
      - '__tests__/**'
  workflow_dispatch:
jobs:
  simple-upload:
    runs-on: ubuntu-latest
    name: Simple Test
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        name: Rinze1
        file: __tests__/${{ github.job }}/shiny-small
        extension: mdb
